language: node_js
node_js: 'node'
addons:
    apt:
      packages:
        - oracle-java8-installer
jdk: oraclejdk8
before_script:
  - java -version
  - bin/./install-solr.sh
  - npm install -g istanbul
  - npm install -g mocha
script:
  - npm test
after_success:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js