language: node_js
node_js: 'node'
jdk:
  - oraclejdk8
before_script:
  - java -version
  - npm install -g istanbul
  - npm install -g mocha
script:
  - bin/./install-solr.sh
  - npm test
after_success:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js