language: node_js
node_js:
  - 'node'
jdk:
 - openjdk7
before_script:
- bin/./install-solr.sh
- npm install -g istanbul
- npm install -g mocha
script: npm test
after_success:
- cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js