sudo: required
language: java
jdk:
  - oraclejdk8
node_js:
  - "5"
node_js: 'node'
before_script:
  - node -v
  - java -version
  - bin/./install-solr.sh
  - npm install -g istanbul
  - npm install -g mocha
  - npm install
script:

  - npm test
after_success:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js